<?php

$gui = new \classes\Component\GUI();
$gui->opendiv('filt', 'col-xs-12 col-sm-4 col-md-3 col-lg-3');
    classes\Component\widget::executeWidgets(array(
       'config/group/widgets/userConfigGroupWidget' => array(),
    ));
$gui->closediv();

$gui->opendiv('filt', 'col-xs-12 col-sm-8 col-md-9 col-lg-9');
    classes\Component\widget::executeWidgets(array(
       'config/form/widgets/userConfigFormWidget' => array('formId'=>$form,'groupId'=>$group),
    ));
$gui->closediv();