<ol class="breadcrumb">
<?php
    foreach($steps as $key => $step){
        if($current_step === $key){$step = "<b>$step</b>";}
        echo "<li>$step</li>";
    }
?>
</ol>
<?php

$gui = new \classes\Component\GUI();

$gui->opendiv('filt', 'col-xs-10 col-xs-offset-1');
    classes\Component\widget::executeWidgets(array(
       'config/form/widgets/userConfigFormWidget' => array('formId'=>$form,'groupId'=>$group,'action'=>$action,'itemId'=>$itemId),
    ));
$gui->closediv();